### ISSUE TITLE
Is it possible to jump to that line on `<CR>`?

### ISSUE THREAD

**Issue by nyngwang** [mrbjarksen/neo-tree-diagnostics.nvim#13]
as title.

**Comment by mrbjarksen** [comment]
If I understand correctly, this should already be the default behavior. Have you mapped `<CR>` to anything other than `open` in your neo-tree config?

**Comment by nyngwang** [comment]
@mrbjarksen Yes. I solved this by adding the `diagnostics.window`:

```lua
window = {
  mappings = { ['<cr'] = 'open', }
}
```
