### ISSUE TITLE
Error in event handler for event neo_tree_buffer_enter[diagnostics.neo_tree_buffer_enter]: .../lua/nui/tree/init.lua:254: Expected Lua number

### ISSUE THREAD

**Issue by nyngwang** [mrbjarksen/neo-tree-diagnostics.nvim#18]
> The commit seems to cause an error. The error is shown on both diagnostics list and neotree filesystem filetree.
> 
> ```
>  Error in event handler for event neo_tree_buffer_enter[diagnostics.neo_tree_buffer_enter]: >  ...im/site/pack/packer/start/nui.nvim/lua/nui/tree/init.lua:254: Expected Lua number
>  ```

_Originally posted by @nyngwang in https://github.com/mrbjarksen/neo-tree-diagnostics.nvim/issues/14#issuecomment-1260898868_

I just tested and found that either true or false on the option `autopreview = ...`, the same error was shown.

**Comment by mrbjarksen** [comment]
My apologies, I don't know how I didn't notice this. I'm working on fixing it but I'm having trouble seeing what's happening. 

Are you sure that `autopreview = false` also gives an error? I'm not seeing the same thing.

**Comment by mrbjarksen** [comment]
I just pushed a commit which fixes things on my end (9a78e75688a9571136246a9e7b0d7aa01e71b51a). If it doesn't work for you, try disabling your event handler, the interplay between them might be causing issues.

**Comment by nyngwang** [comment]
I still got the error if I keep the event as above.

> [...] Error in event handler for event after_render[table: 0x01034d1148]: ...im/site/pack/packer/start/nui.nvim/lua/nui/tree/init.lua:254: Expected Lua number

But then I will assume that the ability to preview on filesystem source will be disabled. Do you have any alternative regarding that?

**Comment by nyngwang** [comment]
After some testing I think this will be helpful: If I call the toggle to open diagnostics.nvim when my cursor is at neo-tree, then no error will be shown.

<img src="https://user-images.githubusercontent.com/24765272/192807371-eb776023-ccd6-4427-84b3-54654029ec41.png" width="600">

**Comment by cseickel** [comment]
@nyngwang The event handler I gave you assumes that you are only using the `filesystem` source and will not have any other sources open. It needs to be re-written to be aware of which source triggered the event.

Maybe auto-preview does need to be handled in core, even if it is enabled and/or configured per source.

**Comment by mrbjarksen** [comment]
> Maybe auto-preview does need to be handled in core, even if it is enabled and/or configured per source.

Yes, I think that would probably be a good idea. My solution was more involved than I originally thought it would be.

**Comment by nyngwang** [comment]
@cseickel Then maybe this could be put into a new issue on neo-tree side and feel free to postpone it if there are issues of higher priority. Good to know that this bug is indeed making neo-tree a more powerful daily tool :)
