### ISSUE TITLE
Support for TODO comments 

### ISSUE THREAD

**Issue by AndOrangutan** [mrbjarksen/neo-tree-diagnostics.nvim#21]
Recently came across your plugin, and neo-tree as a whole, and am really thinking of making the switch. One thing that is kind of holding me back though is the lack of TODO comment support compared to Trouble with `folke/todo-comments.nvim`.
![image](https://user-images.githubusercontent.com/40435989/193473101-f6da8463-b8cb-48b1-a664-2963f80f2166.png)

While that plugin does both highlighting and aggregation of todos, the aggregation is what I really use. That being said, I could totally understand if that isn't within the scope of this project.

Either way, I am looing forward to probably including this plugin and neo-tree in my config rewrite.

**Comment by mrbjarksen** [comment]
Thanks for the suggestion! I do think this is beyond the scope of this project, but I have been looking for different sources to make. This one doesn't seem to be too difficult as a lot of the heavy lifting is done by todo-comments.nvim. I might just give this a go, I'll let you know when I can get around to it.
