### ISSUE TITLE
Control auto-refresh with config option

### ISSUE THREAD

**Issue by cseickel** [mrbjarksen/neo-tree-diagnostics.nvim#23]
I have had some issues with neovim freezing when I do something to produce a lot of errors while the diagnostics source is open. I think I can fix that by adjusting the debounce time, or even just disabling the auto refresh completely.

I can submit a PR if that sounds like a good idea to you. I'm not sure yet what the option would be called, maybe one of:

1. debounce_interval
2. max_refresh_interval ( or is it min? )
3. refresh_interval
4. refresh_delay

That option can either be set to `false` or `-1` to disable it entirely, or there can be another option to `auto_refresh` which can default to `true`.

**Comment by mrbjarksen** [comment]
I'd be happy to add a config option for this, although I'm more worried about the performance. How many diagnostics can the source handle before freezing, and how long is the delay? Maybe making the refresh function async would be worth the effort?

I'll add an option in the meantime, at any rate. I'm thinking `refresh_delay` for the debounce and `refresh_event` to adjust when it fires.

**Comment by cseickel** [comment]
So far so good. I really like the "there are x unprocessed" message, that's a nice touch. I'll keep using it throughout the work day and let you know how it works out.

**Comment by cseickel** [comment]
I think it works perfectly, I'd say it's good for release. 🚀 

Thanks!

**Comment by mrbjarksen** [comment]
Great, thanks!
